---
- name: Create backend directory
  ansible.builtin.file:
    path: "{{ app_dir }}/bin"
    state: 'directory'
    mode: '0755'
    owner: 'www-data'
    group: 'www-data'

- name: Upload backend files
  ansible.builtin.copy:
    src: "{{ api_bin_path }}"
    dest: "{{ app_dir }}/bin/sectxt-api"
    mode: '0755'
    owner: 'www-data'
    group: 'www-data'

- name: Stop backend systemd service
  ansible.builtin.systemd:
    name: 'sectxt-api'
    state: 'stopped'
  failed_when: false

- name: Create backend systemd service
  ansible.builtin.template:
    src: 'templates/sectxt-api.service.j2'
    dest: '/etc/systemd/system/sectxt-api.service'
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Reload backend systemd service
  ansible.builtin.systemd:
    name: 'sectxt-api'
    daemon_reload: yes
    enabled: yes
    state: 'restarted'
