---
- name: Create www-data group
  ansible.builtin.group:
    name: 'www-data'
    state: 'present'

- name: Create www-data user
  ansible.builtin.user:
    name: 'www-data'
    group: 'www-data'
    shell: '/usr/sbin/nologin'
    create_home: no
    system: yes
    state: 'present'

- name: Install Caddy
  ansible.builtin.shell: |
    set -e
    apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --yes --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
    chmod o+r /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    chmod o+r /etc/apt/sources.list.d/caddy-stable.list
    apt update
    apt install -y caddy
  args:
    creates: /usr/bin/caddy
